### PR TITLE
changed colour of UoftHacks and added Apply Here button

### PR DESCRIPTION
**Pull request by kevinle623**
**Description**
need to add url to dashboard

image

### CODE REVIEW

**Comment by annehu2** [comment]
Oh sorry, should have mentioned we want to get rid of the 
image

since apps are now open

**Comment by annehu2** [comment]
I think its missing the interested in sponsoring in the bottom right

**Comment by annehu2** [comment]
Hey! I think on wider screens, "the interested in sponsoring" positioning is off. If it can be aligned with the main banner, that would be great! 
image

**Comment by annehu2** [comment]
Also - Reminder before pushing to main, to add the secret link to our dashboard :D

**Comment by guninwasan** [comment]
amazing. thanks for working on this Kevin!! and thanks for the review Anne 🫡

**Pull request merged**
